### ISSUE TITLE
When X-Forwarded-For is presetn, get_address returns the whole list of IPs

### ISSUE THREAD

**Issue by pmarques** [hivesolutions/appier#14]
The [get_address](https://github.com/hivesolutions/appier/blob/e09ef4b9bf373fcfb455db83ece563bb28655591/src/appier/request.py#L376) method needs to parse the X-Forwarded-For header and return only the first one.
It also needs to check if other headers are used, at least **x-real-ip** and **x-client-ip**.

This is critical to run applications behind proxies.

**Comment by joamag** [comment]
@pmarques nice one
