### ISSUE TITLE
Support for forcing validation type manually

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/appier#2]
## Description

Currently the `_validate()` method uses the validation methods in `validate()` or `validate_new()`, depending on whether the object is new or not. It's useful in some contexts to be able to call the `_validate()` method an be able to tell it which validation methods it should execute, one or the other, without relying on the object being validated.

**Comment by joamag** [comment]
The `self.approve()` method must be used instead with `self.approve(type = "new")` for situations where the new validation is required.
